# 单机版

kind: pipeline
name: server

clone:
  disable: true

platform:
  os: linux
  arch: amd64   // 设置平台

workspace:
  base: /go
  path: .

steps:
- name: clone
  image: docker:git
  commands:
    - pwd
    - echo "clone"
    - git clone http://106.13.128.130:10080/furyx/server.git
    - mv server server-$DRONE_COMMIT_BRANCH  # 修改文件夹名称
    - cd server-$DRONE_COMMIT_BRANCH
    - git checkout $DRONE_COMMIT           # 切换分支
    - ls
- name: copy
  image: appleboy/drone-scp
  when:
    status:
      - success
  settings:
    pull: true
    host:
      from_secret: host
    port:
      from_secret: port
    password:
      from_secret: password
    username:
      from_secret: username
    target:
      from_secret: deploy_path
    source: 
      - ./*
- name: build
  image: appleboy/drone-ssh  #Drone插件通过SSH在远程主机上执行命令
  environment:  
    PJ:  
      from_secret: pj  
    DEPPATH:  
      from_secret: deppath
    DRONE_COMMIT_BRANCH: DRONE_COMMIT_BRANCH
  when:
    status:
      - success
  settings:
    host:
      from_secret: host
    port:
      from_secret: port
    password:
      from_secret: password
    username:
      from_secret: username
    secrets: [ pj, deppath ]
    envs: [ PJ, DEPPATH, DRONE_COMMIT_BRANCH ]
    script:
      - echo $DRONE_COMMIT_BRANCH
      - cd $DEPPATH-$DRONE_COMMIT_BRANCH
      - export GOPROXY=https://athens.azurefd.net
      - export GO111MODULE=on
      - go vet
      - go mod tidy
      - go build -o server-$DRONE_COMMIT_BRANCH ./main.go
      - sh admin.sh restart server-$DRONE_COMMIT_BRANCH
      - sh ./admin.sh status server-$DRONE_COMMIT_BRANCH
- name: notify
  image: drillster/drone-email
  when:
      status: [ success, changed, failure ]
  settings:
    from: 
      from_secret: email_from
    host:
      from_secret: email_host
    port:
      from_secret: email_port
    username:
      from_secret: email_username
    password: 
      from_secret: email_password
    recipients:
      from_secret: email_recipients
    subject: >
      [{{ build.status }}] {{ repo.owner }}/{{ repo.name }} ({{ commit.branch }} - {{ truncate commit.sha 8 }})
    body: >
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
      <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
          <meta name="viewport" content="width=device-width" />
          <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
          <style>
            * {
              margin: 0;
              padding: 0;
              font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
              box-sizing: border-box;
              font-size: 14px;
            }
            body {
              -webkit-font-smoothing: antialiased;
              -webkit-text-size-adjust: none;
              width: 100% !important;
              height: 100%;
              line-height: 1.6;
              background-color: #f6f6f6;
            }
            table td {
              vertical-align: top;
            }
            .body-wrap {
              background-color: #f6f6f6;
              width: 100%;
            }
            .container {
              display: block !important;
              max-width: 600px !important;
              margin: 0 auto !important;
              /* makes it centered */
              clear: both !important;
            }
            .content {
              max-width: 600px;
              margin: 0 auto;
              display: block;
              padding: 20px;
            }
            .main {
              background: #fff;
              border: 1px solid #e9e9e9;
              border-radius: 3px;
            }
            .content-wrap {
              padding: 20px;
            }
            .content-block {
              padding: 0 0 20px;
            }
            .header {
              width: 100%;
              margin-bottom: 20px;
            }
            h1, h2, h3 {
              font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
              color: #000;
              margin: 40px 0 0;
              line-height: 1.2;
              font-weight: 400;
            }
            h1 {
              font-size: 32px;
              font-weight: 500;
            }
            h2 {
              font-size: 24px;
            }
            h3 {
              font-size: 18px;
            }
            hr {
              border: 1px solid #e9e9e9;
              margin: 20px 0;
              height: 1px;
              padding: 0;
            }
            p,
            ul,
            ol {
              margin-bottom: 10px;
              font-weight: normal;
            }
            p li,
            ul li,
            ol li {
              margin-left: 5px;
              list-style-position: inside;
            }
            a {
              color: #348eda;
              text-decoration: underline;
            }
            .last {
              margin-bottom: 0;
            }
            .first {
              margin-top: 0;
            }
            .padding {
              padding: 10px 0;
            }
            .aligncenter {
              text-align: center;
            }
            .alignright {
              text-align: right;
            }
            .alignleft {
              text-align: left;
            }
            .clear {
              clear: both;
            }
            .alert {
              font-size: 16px;
              color: #fff;
              font-weight: 500;
              padding: 20px;
              text-align: center;
              border-radius: 3px 3px 0 0;
            }
            .alert a {
              color: #fff;
              text-decoration: none;
              font-weight: 500;
              font-size: 16px;
            }
            .alert.alert-warning {
              background: #ff9f00;
            }
            .alert.alert-bad {
              background: #d0021b;
            }
            .alert.alert-good {
              background: #68b90f;
            }
            @media only screen and (max-width: 640px) {
              h1,
              h2,
              h3 {
                font-weight: 600 !important;
                margin: 20px 0 5px !important;
              }
              h1 {
                font-size: 22px !important;
              }
              h2 {
                font-size: 18px !important;
              }
              h3 {
                font-size: 16px !important;
              }
              .container {
                width: 100% !important;
              }
              .content,
              .content-wrapper {
                padding: 10px !important;
              }
            }
          </style>
        </head>
        <body>
          <table class="body-wrap">
            <tr>
              <td></td>
              <td class="container" width="600">
                <div class="content">
                  <table class="main" width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                      {{#success build.status}}
                        <td class="alert alert-good">
                          <a href="{{ build.link }}">
                            Successful build #{{ build.number }}
                          </a>
                        </td>
                      {{else}}
                        <td class="alert alert-bad">
                          <a href="{{ build.link }}">
                            Failed build #{{ build.number }}
                          </a>
                        </td>
                      {{/success}}
                    </tr>
                    <tr>
                      <td class="content-wrap">
                        <table width="100%" cellpadding="0" cellspacing="0">
                          <tr>
                            <td>
                              Repo:
                            </td>
                            <td>
                              {{ repo.owner }}/{{ repo.name }}
                            </td>
                          </tr>
                          <tr>
                            <td>
                              Author:
                            </td>
                            <td>
                              {{ commit.author.name }} ({{ commit.author.email }})
                            </td>
                          </tr>
                          <tr>
                            <td>
                              Branch:
                            </td>
                            <td>
                              {{ commit.branch }}
                            </td>
                          </tr>
                          <tr>
                            <td>
                              Commit:
                            </td>
                            <td>
                              {{ truncate commit.sha 8 }}
                            </td>
                          </tr>
                          <tr>
                            <td>
                              Started at:
                            </td>
                            <td>
                              {{ datetime build.created "Mon Jan 2 15:04:05 MST 2006" "Local" }}
                            </td>
                          </tr>
                        </table>
                        <hr>
                        <table width="100%" cellpadding="0" cellspacing="0">
                          <tr>
                            <td>
                              {{ commit.message }}
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </div>
              </td>
              <td></td>
            </tr>
          </table>
        </body>
      </html>

