linters-settings: # 配置地址 https://golangci-lint.run/usage/linters
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 3
    min-occurrences: 10 #触发问题的常量字符串计数的最小出现次数，默认为3
  gocritic: # https://golangci-lint.run/usage/linters/#gocritic
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - unnamedResult
    settings:
      captLocal: # must be valid enabled check name
        # whether to restrict checker to params only (default true)
        paramsOnly: true
      elseif:
        # whether to skip balanced if-else pairs (default true)
        skipBalanced: true
      hugeParam:
        # size in bytes that makes the warning trigger (default 80)
        sizeThreshold: 256
  gove:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true
  golint:
    # 默认值为0.8
    min-confidence: 0.8
  revive:
    rules:
      - name: var-naming
        arguments:
          - #白名单
            - video_info
            - admin_user_role
            - company_introduction
            - no_router
            - admin_department
            - tag_to_article
            - admin_login_log
            - admin_role
            - admin_menu
            - website_config
            - admin_operation_log
            - admin_role_menu
  gomnd:
    settings:
      mnd:
        ignored-functions: ".SetLifeTime" # 排除的函数名称正则表达式模式，逗号分隔列表。

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - exhaustive
    - goconst # 查找可以被常量替换的重复字符串
    - gocritic # 提供检查错误、性能和样式问题的诊断。 无需通过动态规则重新编译即可扩展。 动态规则是使用 AST 模式、过滤器、报告消息和可选建议以声明方式编写的。
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint # 报告格式错误或不充分的 nolint 指令
    - nakedret
    - prealloc
    - predeclared
#    - revive # 用于 Go 的快速、可配置、可扩展、灵活且美观的 linter。直接替换 golint。
    - staticcheck
    - structcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wsl

run:
  issues-exit-code: 1