package routes

import (
	"fagin/app"
	"fagin/app/controllers/api"
	"fagin/app/errno"
	"fagin/app/middleware" // 中间件
	_ "fagin/docs"         // docs is generated by Swag CLI, you have to import it.
	"fagin/pkg/router"
	"github.com/gin-gonic/gin"
	"net/http"
	"time"
)

var Api = router.Group("api")

func init() {
	// 404
	router.NoRoute(Api.BasePath(), func(ctx *gin.Context) {
		app.JsonResponseWithStatus(ctx, http.StatusNotFound, errno.NotFound, gin.H{"m": "api 404"})
	})

	// 测试限流中间件
	Api.Use(middleware.RateLimitMiddleware(5, 10*time.Second, func(ctx *gin.Context) {
		ctx.String(http.StatusServiceUnavailable, "服务器繁忙")
	}))

	Api.GET("/", api.IndexController.Index)

	V1 := Api.Group("/v1")
	{
		// 用户登陆 获取token
		V1.POST("/login", api.AuthController.Login)
		// 注册用户
		V1.POST("/register", api.UserController.Register)

		// 视频
		video := Api.Group("/video")
		{
			// 观看视频
			video.GET("/play/:id", api.VideoController.PlayVideo)
		}

		// 需要登陆才能调用
		V1.Use(middleware.Auth.IsLogin(), middleware.Auth.AuthCheckRole())
		{
			V1.GET("/", api.IndexController.Index)
			V1.POST("/", api.IndexController.Index)
			V1.DELETE("/", api.IndexController.Index)
			V1.GET("/logout", api.AuthController.Logout)
			V1.GET("/add", api.AuthController.CreateUser)

			//用户组
			user := V1.Group("/user")
			{
				// 用户列表
				user.GET("/", api.UserController.UserList)
				id := user.Group("/:id")
				{
					// 查看用户
					id.GET("/", api.UserController.ShowUser)
					// 更新用户
					id.PATCH("/", api.UserController.UpdateUser)
					// 删除用户
					id.DELETE("/", api.UserController.DestroyUser)
				}
			}
		}

	}
}
