package migrations

import (
	"fagin/config"
	"fagin/pkg/migrate"
	"time"

	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func init() {
	type AdminMenu struct {
		ID        uint `gorm:"primarykey"`
		CreatedAt time.Time
		UpdatedAt time.Time
		DeletedAt gorm.DeletedAt `gorm:"index"`

		ParentID      uint   `gorm:"not null;index;default:0;comment:父id;column:parent_id;"`
		Paths         string `gorm:"type:varchar(128);not null;default:'';comment:层级路径 0-1-2-;column:paths;"`
		Type          int    `gorm:"not null;index:idx_type_path_method,priority:1;default:0;comment:类型: 0:目录; 1:菜单; 2:权限;column:type;"`
		Name          string `gorm:"type:varchar(32);not null;default:'';comment:名称;column:name;"`
		Permission    string `gorm:"type:varchar(64);not null;default:'';comment:权限标记;column:permission;"`
		Title         string `gorm:"type:varchar(32);not null;default:'';comment:标题;column:title;"`
		Component     string `gorm:"type:varchar(255);not null;default:'';comment:组件名称;column:component;"`
		Path          string `gorm:"type:varchar(255);not null;index:idx_type_path_method,priority:2;default:'';comment:路由地址;column:path;"`
		Method        string `gorm:"type:varchar(16);not null;index:idx_type_path_method,priority:3;default:'';comment:请求方法;column:method;"`
		Redirect      string `gorm:"type:varchar(255);not null;default:'';comment:重定向;column:redirect;"`
		FrameSrc      string `gorm:"type:varchar(255);not null;default:'';comment:内嵌iframe的地址;column:frame_src;"`
		CurrentActive string `gorm:"type:varchar(255);not null;default:'';comment:当前激活的菜单;column:current_active;"`
		Icon          string `gorm:"type:varchar(128);not null;default:'';comment:图标;column:icon;"`
		IsShow        uint8  `gorm:"not null;default:1;comment:展示状态: 0=>隐藏 1=>展示;column:is_show;"`
		IsHideChild   uint8  `gorm:"not null;default:0;comment:是否隐藏子菜单: 0=>展示 1=>隐藏;column:is_hide_child"`
		IsNoCache     uint8  `gorm:"not null;default:0;comment:是否无缓存: 0=>否 1=>是;column:is_no_cache"`
		Sort          uint   `gorm:"not null;default:100;comment:排序，数字越大越靠前;column:sort"`
		Status        uint8  `gorm:"not null;default:1;comment:状态 0:关闭 1开启;column:status"`
	}

	migrate.Add(&gormigrate.Migration{
		ID: "20220826000258_20200818102853_create_admin_menu_table.go",
		Migrate: func(tx *gorm.DB) error {
			options := ""
			if config.DBDriverMysql == config.Database().Driver() {
				options = "COMMENT='后台菜单表'"
			}

			err := tx.Set("gorm:table_options", options).
				Migrator().CreateTable(&AdminMenu{})
			if err != nil {
				return err
			}

			menus := &[]AdminMenu{
				{
					ID:            1,
					ParentID:      0,
					Paths:         "0-",
					Type:          0,
					Name:          "Dashboard",
					Permission:    "",
					Title:         "仪表盘",
					Component:     "LAYOUT",
					Path:          "/dashboard",
					Method:        "",
					Redirect:      "/dashboard/analysis",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:dashboard-outlined",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            2,
					ParentID:      1,
					Paths:         "0-1-",
					Type:          1,
					Name:          "Workbench",
					Permission:    "dashboard.workbench",
					Title:         "工作台",
					Component:     "/dashboard/workbench/index",
					Path:          "/dashboard/workbench",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:windows-outlined",
					IsShow:        1,
					IsHideChild:   1,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            3,
					ParentID:      1,
					Paths:         "0-1-",
					Type:          1,
					Name:          "Analysis",
					Permission:    "dashboard.analysis",
					Title:         "分析页",
					Component:     "/dashboard/analysis/index",
					Path:          "/dashboard/analysis",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:area-chart-outlined",
					IsShow:        1,
					IsHideChild:   1,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            4,
					ParentID:      0,
					Paths:         "0-",
					Type:          0,
					Name:          "System",
					Permission:    "",
					Title:         "系统管理",
					Component:     "LAYOUT",
					Path:          "/system",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:setting-outlined",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            7,
					ParentID:      4,
					Paths:         "0-4-",
					Type:          1,
					Name:          "AccountManagement",
					Permission:    "admin.system.account",
					Title:         "账号管理",
					Component:     "/system/account/index",
					Path:          "/system/account",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:team-outlined",
					IsShow:        1,
					IsHideChild:   1,
					IsNoCache:     0,
					Sort:          101,
					Status:        1,
				},
				{
					ID:            8,
					ParentID:      4,
					Paths:         "0-4-",
					Type:          1,
					Name:          "MenuManagement",
					Permission:    "admin.system.menu",
					Title:         "菜单管理",
					Component:     "/system/menu/index",
					Path:          "/system/menu",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:menu-outlined",
					IsShow:        1,
					IsHideChild:   1,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            9,
					ParentID:      4,
					Paths:         "0-4-",
					Type:          1,
					Name:          "RoleManagement",
					Permission:    "admin.system.role",
					Title:         "角色管理",
					Component:     "/system/role/index",
					Path:          "/system/role",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:user-switch-outlined",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            10,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          1,
					Name:          "AccountDetail",
					Permission:    "admin.system.account_detail",
					Title:         "账号详情",
					Component:     "/system/account/AccountDetail",
					Path:          "/system/account_detail/:id",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "/system/account",
					Icon:          "ant-design:user-outlined",
					IsShow:        0,
					IsHideChild:   1,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            13,
					ParentID:      0,
					Paths:         "0-",
					Type:          0,
					Name:          "Monitor",
					Permission:    "",
					Title:         "系统监控",
					Component:     "LAYOUT",
					Path:          "/monitor",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:monitor-outlined",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            14,
					ParentID:      13,
					Paths:         "0-13-",
					Type:          1,
					Name:          "LoginLogManagement",
					Permission:    "admin.monitor.login-log",
					Title:         "登录日志",
					Component:     "/monitor/login-log/index",
					Path:          "/monitor/login-log",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:login-outlined",
					IsShow:        1,
					IsHideChild:   1,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            15,
					ParentID:      13,
					Paths:         "0-13-",
					Type:          1,
					Name:          "OperLogManagement",
					Permission:    "admin.monitor.oper-log",
					Title:         "操作日志",
					Component:     "/monitor/oper-log/index",
					Path:          "/monitor/oper-log",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:control-outlined",
					IsShow:        1,
					IsHideChild:   1,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            16,
					ParentID:      4,
					Paths:         "0-4-",
					Type:          1,
					Name:          "DepartmentManagement",
					Permission:    "admin.system.department",
					Title:         "部门管理",
					Component:     "/system/department/index",
					Path:          "/system/department",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:apartment-outlined",
					IsShow:        1,
					IsHideChild:   1,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            17,
					ParentID:      16,
					Paths:         "0-4-16-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.department:query",
					Title:         "部门查询",
					Component:     "",
					Path:          "/admin/api/departments",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        0,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            18,
					ParentID:      16,
					Paths:         "0-4-16-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.department:detail",
					Title:         "部门详情",
					Component:     "",
					Path:          "/admin/api/departments/:id",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            19,
					ParentID:      16,
					Paths:         "0-4-16-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.department:create",
					Title:         "新增部门",
					Component:     "",
					Path:          "/admin/api/departments",
					Method:        "POST",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            20,
					ParentID:      16,
					Paths:         "0-4-16-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.department:update",
					Title:         "更新部门",
					Component:     "",
					Path:          "/admin/api/departments/:id",
					Method:        "PUT",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            21,
					ParentID:      16,
					Paths:         "0-4-16-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.department:delete",
					Title:         "删除部门",
					Component:     "",
					Path:          "/admin/api/departments/:id",
					Method:        "DELETE",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        0,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            22,
					ParentID:      9,
					Paths:         "0-4-9-",
					Type:          2,
					Name:          "LoginLogManagement",
					Permission:    "admin.system.role:query",
					Title:         "角色查询",
					Component:     "",
					Path:          "/admin/api/roles",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            23,
					ParentID:      9,
					Paths:         "0-4-9-",
					Type:          2,
					Name:          "LoginLogManagement",
					Permission:    "admin.system.role:detail",
					Title:         "角色详情",
					Component:     "",
					Path:          "/admin/api/roles/:id",
					Method:        "",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            24,
					ParentID:      9,
					Paths:         "0-4-9-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.role:create",
					Title:         "角色新增",
					Component:     "",
					Path:          "/admin/api/roles",
					Method:        "POST",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            25,
					ParentID:      9,
					Paths:         "0-4-9-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.role:update",
					Title:         "角色更新",
					Component:     "",
					Path:          "/admin/api/roles/:id",
					Method:        "PUT",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            26,
					ParentID:      9,
					Paths:         "0-4-9-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.role:delete",
					Title:         "角色删除",
					Component:     "",
					Path:          "/admin/api/roles/:id",
					Method:        "DELETE",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            27,
					ParentID:      9,
					Paths:         "0-4-9-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.role:key-exists",
					Title:         "角色key是否存在",
					Component:     "",
					Path:          "/admin/api/roles/key",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            28,
					ParentID:      9,
					Paths:         "0-4-9-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.role:update-status",
					Title:         "更改状态",
					Component:     "",
					Path:          "/admin/api/roles/:id/status",
					Method:        "PUT",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            29,
					ParentID:      9,
					Paths:         "0-4-9-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.role:menus",
					Title:         "所有菜单",
					Component:     "",
					Path:          "/admin/api/roles/menus",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            30,
					ParentID:      8,
					Paths:         "0-4-8-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.menu:query",
					Title:         "菜单查询",
					Component:     "",
					Path:          "/admin/api/menus",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            31,
					ParentID:      8,
					Paths:         "0-4-8-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.menu:detail",
					Title:         "菜单详情",
					Component:     "",
					Path:          "/admin/api/menus/:id",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            32,
					ParentID:      8,
					Paths:         "0-4-8-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.menu:create",
					Title:         "新增菜单",
					Component:     "",
					Path:          "/admin/api/menus",
					Method:        "POST",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            33,
					ParentID:      8,
					Paths:         "0-4-8-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.menu:update",
					Title:         "更新菜单",
					Component:     "",
					Path:          "/admin/api/menus/:id",
					Method:        "PUT",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            34,
					ParentID:      8,
					Paths:         "0-4-8-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.menu:delete",
					Title:         "删除菜单",
					Component:     "",
					Path:          "/admin/api/menus/:id",
					Method:        "DELETE",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            35,
					ParentID:      8,
					Paths:         "0-4-8-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.menu:all",
					Title:         "所有菜单",
					Component:     "",
					Path:          "/admin/api/menus/all",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            36,
					ParentID:      15,
					Paths:         "0-13-15-",
					Type:          2,
					Name:          "",
					Permission:    "admin.monitor.oper-log:query",
					Title:         "操作日志查询",
					Component:     "",
					Path:          "/admin/api/operation/logs",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            37,
					ParentID:      15,
					Paths:         "0-13-15-",
					Type:          2,
					Name:          "",
					Permission:    "admin.monitor.oper-log:detail",
					Title:         "操作日志详情",
					Component:     "",
					Path:          "/admin/api/operation/logs/:id",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            38,
					ParentID:      14,
					Paths:         "0-13-14-",
					Type:          2,
					Name:          "",
					Permission:    "admin.monitor.login-log:query",
					Title:         "登录日志查询",
					Component:     "",
					Path:          "/admin/api/login-logs",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            39,
					ParentID:      14,
					Paths:         "0-13-14-",
					Type:          2,
					Name:          "",
					Permission:    "admin.monitor.login-log:detail",
					Title:         "登录日志详情",
					Component:     "",
					Path:          "/admin/api/login-logs/:id",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            40,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:query",
					Title:         "用户查询",
					Component:     "",
					Path:          "/admin/api/accounts",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            41,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:detail",
					Title:         "用户详情",
					Component:     "",
					Path:          "/admin/api/accounts/:id",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            42,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:create",
					Title:         "新增用户",
					Component:     "",
					Path:          "/admin/api/accounts",
					Method:        "POST",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            43,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:update",
					Title:         "更新用户",
					Component:     "",
					Path:          "/admin/api/accounts/:id",
					Method:        "PUT",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            44,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:delete",
					Title:         "删除用户",
					Component:     "",
					Path:          "/admin/api/accounts/:id",
					Method:        "DELETE",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            45,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:update-pwd",
					Title:         "用户更新密码",
					Component:     "",
					Path:          "/admin/api/accounts/:id/pwd",
					Method:        "PUT",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            46,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:update-status",
					Title:         "用户更新状态",
					Component:     "",
					Path:          "/admin/api/accounts/:id/status",
					Method:        "PUT",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            47,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:logout",
					Title:         "强制下线",
					Component:     "",
					Path:          "/admin/api/accounts/:id/logout",
					Method:        "POST",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            48,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:exists",
					Title:         "账号名是否已存在",
					Component:     "",
					Path:          "/admin/api/accounts/exists",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            49,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:roles",
					Title:         "角色列表",
					Component:     "",
					Path:          "/admin/api/accounts/roles",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
				{
					ID:            50,
					ParentID:      7,
					Paths:         "0-4-7-",
					Type:          2,
					Name:          "",
					Permission:    "admin.system.account:departments",
					Title:         "部门列表",
					Component:     "",
					Path:          "/admin/api/accounts/departments",
					Method:        "GET",
					Redirect:      "",
					FrameSrc:      "",
					CurrentActive: "",
					Icon:          "ant-design:api-twotone",
					IsShow:        1,
					IsHideChild:   0,
					IsNoCache:     0,
					Sort:          100,
					Status:        1,
				},
			}

			err = tx.Create(menus).Error
			if err != nil {
				return err
			}

			if config.DBDriverPostgres == config.Database().Driver() {
				// 设定自增序列
				err = tx.Exec(`SELECT setval( 'admin_menus_id_seq', ( SELECT MAX ( ID ) FROM admin_menus ) )`).Error
				if err != nil {
					return err
				}
			}

			return nil
		},
		Rollback: func(tx *gorm.DB) error {
			return tx.Migrator().DropTable(&AdminMenu{})
		},
	})
}
